name: testing sample pipeline
trigger:
  - master
resources:
  - repo: self
  
stages:
    - stage: runscript1
      displayName: runscript1 
      jobs:
      - job: buildrunbashscript
        displayName: runbashscript
        pool: dev
        steps:
          - task: ShellScript@2
            displayName: runshellscripts
            inputs:
              scriptPath: shell.sh
      - job: buildrunbashscript
        displayName: runbashscript
        pool: prod      
        steps:
          - task: PowerShell@2
            displayName: runpowershellscripts
            inputs:
              filePath: powershell.ps              
    
    
