## testing sample pipeline
trigger:
  - master
resources:
  - repo: self
  
stages:
    - stage: Build Code
      displayName: Build 
      jobs:
      - job: build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: buildAndPush
            inputs:
              command: buildAndPush
              containerRegistry: dockerconection1
              repository: kharatramesh/git2
              tags: |
                  azuredemo1
  
    
    
